# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        token_format: access_token
    - uses: 'docker/login-action@v1'
      with:
        registry: '${{ vars.GCP_CONTAINER_REPOSITORY }}'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: bootBuildImage --imageName ghcr.io/${{ github.repository }}
    - name: Push
      run: |
        docker push ghcr.io/${{ github.repository }}
        docker tag ghcr.io/${{ github.repository }} ${{ vars.GCP_CONTAINER_REPOSITORY }}/${{ vars.GCP_CONTAINER_NAME }}:$GITHUB_SHA
        docker push ${{ vars.GCP_CONTAINER_REPOSITORY }}/${{ vars.GCP_CONTAINER_NAME }}:$GITHUB_SHA
